### ISSUE TITLE
Lack of redirect_url on create bill?

### ISSUE THREAD

**Issue by lxon** [jomweb/billplz#13]
Hi, 

By referring to https://github.com/jomweb/billplz/blob/master/src/Three/Bill.php
I can't set the redirect_url parameter. 
Is there anything I miss out?

**Comment by crynobone** [comment]
You can use the `$optional['redirect_url']` parameter.

**Comment by lxon** [comment]
ohh, thanks!

**Comment by zarulizham** [comment]
Hi, where is the right place to use `$optional['redirect_url']` parameter? Is there any example?

**Comment by zarulizham** [comment]
Never mind, just figured out myself. Great framework BTW 👍🏻
