### ISSUE TITLE
Enable handling callbacks

### ISSUE THREAD

**Issue by zulfajuniadi** [jomweb/billplz#2]
I'm sure there is more elegant way to handle incoming callbacks from BillPlz.

**Comment by crynobone** [comment]
Just added #3 

This should allow us to parse webhook `POST` data using the following syntax.

```php
$sanitizer = new Billplz\Sanitizer();

$response = $sanitizer->to($_POST);
```

At the moment this would convert `amount` and `paid_amount` to `Money\Money` and `due_at` to `DateTime`.

**Comment by crynobone** [comment]
You can now do this.

```php
$billplz->bill()->webhook($_POST);
```

with Laravel

```php
$billplz->bill()->webhook($request->all());
```

Update the deps to `"jomweb/billplz": "^0.5"` for now.
