### ISSUE TITLE
Laravel compatibility

### ISSUE THREAD

**Issue by blu94** [jomweb/billplz#35]
Can this package use in Laravel 5.5, 
And i found "jomweb/billplz-laravel" [](https://github.com/jomweb/billplz-laravel),
But the documentation doesn't include any tutorial of initalize a bill, is the same with current package???

**Comment by crynobone** [comment]
As you can see from <https://github.com/jomweb/billplz-laravel/blob/master/composer.json#L23> `jomweb/billplz-laravel` is already requiring this package.
