### ISSUE TITLE
Purpose and usage of creating Transaction , Banking

### ISSUE THREAD

**Issue by blu94** [jomweb/billplz#36]
I'm using this package along with Laravel 5.5, and i have successfully create a bill, and redirect to the Billplz billing page and able to complete it in sandbox mode, this package is great.

But i have a question, after bill in Billplz is paid successfully, the record in Billplz account also shown "Paid", is that compulsory to create/ run "Transaction" and "Banking" step mention in documentation??

If i am not running, go through the "Transaction" and "Banking" step, will it affect the payment that paid by user?? like the payment is not complete or something?? (status show paid, result also show paid)

And most important thing is what is the "Purpose" of running "Transaction" and "Banking" step??

![image](https://user-images.githubusercontent.com/16028996/42305027-9df97032-805b-11e8-98ee-6e5accb01b3a.png)
![image](https://user-images.githubusercontent.com/16028996/42305057-cc8a950c-805b-11e8-9957-8692606af1db.png)

**Comment by crynobone** [comment]
As mentioned before we are not Billplz employee nor do we have access to the internal process. This project was developed based on the Online API Documentation available via <https://billplz.com/api>. So if you have any issue understanding the flow it is best to consult the Billplz Team via [Facebook Group](https://www.facebook.com/groups/billplzdevjam/)
