### ISSUE TITLE
Callback not triggered

### ISSUE THREAD

**Issue by zarulizham** [jomweb/billplz#37]
I am using staging environment but when I check access.log, there's no callback URL being accessed.

**Comment by wzul** [comment]
Usually server firewall block the incoming connection. Maybe checking the server firewall may helps.

**Comment by zarulizham** [comment]
I've check the firewall and the server accepting all incoming from port 80 and 443.

**Comment by crynobone** [comment]
This project was developed based on the Online API Documentation available via <https://billplz.com/api>, we are not Billplz employee nor do we have access to the internal process. We would prefer to limit issues posted here related to bug/features from our code and not using Billplz in general.

Please redirect all usage issue to the Billplz Team via [Facebook Group](https://www.facebook.com/groups/billplzdevjam/) or email them to [team@billplz.com](mailto:team@billplz.com)
