### ISSUE TITLE
[Suggestion] Using array as a single params on bill creation.

### ISSUE THREAD

**Issue by rained23** [jomweb/billplz#4]
Example

```
$bill->create($collectionId, array $params = []) 
```
or
```
$bill->create(array $params = [])
```

I think by using this version will enable more freedom on how they might use the method itself.
Plus improving the speed of the code without needing to do array_merge.

I am adding this to my fork, I can submit PR if you like the idea.

**Comment by crynobone** [comment]
> I think by using this version will enable more freedom on how they might use the method itself.
Plus improving the speed of the code without needing to do array_merge.

The problem with this is that it doesn't actually separate `required` with `optional` structure, this making it hard to know what's needed and what's not needed when making any API call.

As an example you can simple do 

```php
$collection->create(['foo' => 'bar']); // without sending `title`
``` 

Additionally, once we set the minimum to PHP7 we can start to typehint scalar parameter (as explain in https://laracasts.com/series/php7-up-and-running/episodes/2)

```php

class Bill extends Request
{
    /**
     * Create a new bill.
     *
     * @param  string  $collectionId
     * @param  string  $email
     * @param  string  $mobile
     * @param  string  $name
     * @param  \Money\Money|int  $amount
     * @param  string  $callbackUrl
     * @param  string  $description
     * @param  array  $optional
     *
     * @throws  \InvalidArgumentException
     *
     * @return \Laravie\Codex\Response
     */
    public function create(
        string $collectionId,
        string $email,
        string $mobile,
        string $name,
        $amount,
        string $callbackUrl,
        string $description,
        array $optional = []
    ) : \Laravie\Codex\Response {
       //
    }
}
```

**Comment by rained23** [comment]
Okay, I get the point why it ts designed that way now.

I actually suggest this because I want to make bill with collection_id only, 
so I can receive the status of collection existence. 

I just feel bad to write entire full create() just for a hack.

I think I need to scratch Billplz back a bit for their API limitation.

**Comment by crynobone** [comment]
I'm not the internal member/staff of Billplz so therefore I need to depends on the official documentation. I'm not sure you possible to just create a bill with just `$collection_id` and make sure that this would still exist (if they fix it on their side).

![screen shot 2016-08-24 at 7 09 52 am](https://cloud.githubusercontent.com/assets/172966/17912991/c90a7320-69c9-11e6-9f8d-dcc0627b709d.png)

**Comment by rained23** [comment]
Currently the only way to check collection exist or not. Well yeah, not an official way.

**Comment by crynobone** [comment]
This is something that maybe that need to be officially brought up with @billplz team

**Comment by crynobone** [comment]
https://www.facebook.com/groups/billplzdevjam/permalink/1791908761089102/

For now I guess you should just do:

```php
$bill->create($collectionId, null, null, null, 0, null, null);
```

and then catch the error response.

**Comment by fahribaharudin** [comment]
So how to include the redirect_url when create a bill?

**Comment by rained23** [comment]
use the last params
