### ISSUE TITLE
REDIRECT AFTER PAYMENT

### ISSUE THREAD

**Issue by Naravyb** [jomweb/billplz#41]
Hello, i want to build redirect after the payment but i have the problem when i execute

> Expected $billplz to be an array! 

above is a message when I use $bill->redirect($_GET)

and i want to asking again, how do you know json from $bill->redirect when the order has been completed or is successful?

Thank you.

**Comment by crynobone** [comment]
Feel free to read the documentation.

* [Basic Redirection](https://www.billplz.com/api#basic-redirect_url)
* [X-Signature Redirection](https://www.billplz.com/api#x-signature-redirect_url)
